### ISSUE TITLE
Old dependencies on Raspberry Pi (armv6h)

### ISSUE THREAD

**Issue by nafets227** [VDR4Arch/vdr4arch#133] opened 2016-03-06 19:13 UTC
when upgrading my Arch on Raspberry, I break the VDR4arch packages I use; I had to downgrade following packages:
ffmpeg 1:2.8.6-2 insetad of 1:3.0-1
libcec-rpi 3.0.1-3 insetad of 3.1.0-1
libplatform 1.0.10-2 instead of 2.0.1-1

Can you rebuild the packages on the vdr4arch repo? Actually the last packages are dated 15.10.2015...

**Comment by CReimer** [comment] 2016-03-09 20:29
Duplicate of #122

**Closed by CReimer** 2016-03-09 20:29 UTC
